ARG N8N_VERSION=1.14.2

FROM n8nio/n8n:$N8N_VERSION

ARG PGPASSWORD
ARG PGHOST
ARG PGPORT
ARG PGDATABASE
ARG PGUSER

ARG N8N_ENCRYPTION_KEY
ARG N8N_EDITOR_BASE_URL
ARG GENERIC_TIMEZONE
ARG TZ
ARG PORT

ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_DATABASE=$PGDATABASE
ENV DB_POSTGRESDB_HOST=$PGHOST
ENV DB_POSTGRESDB_PORT=$PGPORT
ENV DB_POSTGRESDB_USER=$PGUSER
ENV DB_POSTGRESDB_PASSWORD=$PGPASSWORD

CMD ["start"]
